version: "3"

volumes:
    influxdb:
    influxdb2:

services:
    #telegraf:
    #    build: telegraf
    #    environment:
    #        CLIENT_ID: ${CLIENT_ID}
    #        CLIENT_SECRET: ${CLIENT_SECRET}
    #        CALLBACK_URL: ${CALLBACK_URL}
    #        CODE: ${CODE}
    #    volumes:
    #        - ./res/fitbit.sh:/var/scripts/fitbit/fitbit.sh

    influxdb:
        image: influxdb:2.0
        expose:
            - "8086"
        ports:
            - 8086:8086
        environment:
            DOCKER_INFLUXDB_INIT_USERNAME=mainuser
            DOCKER_INFLUXDB_INIT_PASSWORD=password
            DOCKER_INFLUXDB_INIT_ORG=projectterris
            DOCKER_INFLUXDB_INIT_BUCKET=bucket
        volumes:
            - influxdb:/var/lib/influxdb
            - influxdb2:/var/lib/influxdb2

    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        